name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "No contributions to this repository will be accepted. If desired, you may [open an issue](https://github.com/Anaminus/roblox-library/issues/new) instead."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
